const SUPABASE_URL = 'https://bigadvelsjvpxagllqkx.supabase.co';
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJpZ2FkdmVsc2p2cHhhZ2xscWt4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODYxMzEzMTAsImV4cCI6MjEwMTcwNzMxMH0.RYIHD5Qwmaq0IIrfJaAWWqRCiv3fgh0d3TNRqxoN08g'; 

const db = supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);